# Generated by Django 4.0 on 2022-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_cagniote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagniote',
            name='sommeRecolter',
            field=models.FloatField(default=0),
        ),
    ]
