# Generated by Django 3.2.9 on 2022-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('demande', 'demande'), ('don', 'don')], default='demande', max_length=10),
        ),
    ]
