# Generated by Django 3.2.9 on 2022-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20220531_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(max_length=255)),
                ('daira_name', models.CharField(max_length=255)),
                ('wilaya_name', models.CharField(max_length=255)),
            ],
        ),
    ]
