# Generated by Django 3.2.9 on 2022-05-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_cagniote_sommerecolter'),
        ('authentification', '0003_annonce_type'),
    ]

    operations = [
    ]
