# Generated by Django 3.2.9 on 2022-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='wilaya_code',
            field=models.IntegerField(default=0),
        ),
    ]
