# Generated by Django 4.0.4 on 2022-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_merge_20220525_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_association',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contenu',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
