# Generated by Django 4.0 on 2022-05-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_user_is_association_user_is_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagniote',
            name='arret',
            field=models.BooleanField(default=False),
        ),
    ]
