# Generated by Django 3.2.9 on 2022-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_delete_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='localisation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('commune_name', models.CharField(max_length=255)),
                ('daira_name', models.CharField(max_length=255)),
                ('wilaya_code', models.IntegerField(default=0)),
                ('wilaya_name', models.CharField(max_length=255)),
            ],
        ),
    ]
