# Generated by Django 3.2.9 on 2022-06-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localisation',
            name='wilaya_code',
        ),
    ]
