# Generated by Django 4.0 on 2022-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_cagniote_arret'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
