# Generated by Django 4.0 on 2022-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_association_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='signial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='signial',
            field=models.IntegerField(default=0),
        ),
    ]
