# Generated by Django 4.0 on 2022-06-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='adresse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentification.localisation'),
        ),
        migrations.AddField(
            model_name='physicaluser',
            name='adresse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentification.localisation'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.localisation'),
        ),
    ]
