# Generated by Django 3.2.9 on 2022-06-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_association_adresse_physicaluser_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='category',
            field=models.TextField(choices=[('Alimentaire', 'Alimentaire'), ('Medical', 'Medical'), ('Vestimentaire', 'Vestimentaire'), ('Educatif', 'Educatif'), ('Financière', 'Financière'), ('Autre', 'Autre')], default='Autre', max_length=50),
        ),
    ]
