# Generated by Django 3.2.9 on 2022-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_annonce_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
