# Generated by Django 4.0 on 2022-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_auto_20220612_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='file',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
