# Generated by Django 4.0 on 2022-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_alter_association_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='arret',
            field=models.BooleanField(default=False),
        ),
    ]
