# Generated by Django 4.0.5 on 2022-06-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_benevole_arret'),
        ('authentification', '0014_rename_contenu_notification_notification'),
    ]

    operations = [
    ]
