# Generated by Django 4.0.4 on 2022-05-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField(max_length=400)),
                ('type', models.CharField(choices=[('Demande', 'Demande'), ('Don', 'Don')], max_length=10)),
                ('image', models.BinaryField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cagniote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('sommeDemander', models.FloatField()),
                ('sommeRecolter', models.FloatField()),
                ('raison', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=400)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=400)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(null=True)),
                ('willaya', models.IntegerField(choices=[(1, 'Adrar'), (2, 'Chlef'), (3, 'Laghouat'), (4, 'Oum-El-Bouaghi'), (5, 'Batna'), (6, 'Béjaïa'), (7, 'Biskra'), (8, 'Béchar'), (9, 'Blida'), (10, 'Bouira'), (11, 'Tamanrasset'), (12, 'Tébessa'), (13, 'Tlemcen'), (14, 'Tiaret'), (15, 'Tizi-Ouzou'), (16, 'Alger'), (17, 'Djelfa'), (18, 'Jijel'), (19, 'Sétif'), (20, 'Saïda'), (21, 'Skikda'), (22, 'Sidi Bel'), (23, 'Annaba'), (24, 'Guelma'), (25, 'Constantine'), (26, 'Médéa'), (27, 'Mostaganem'), (28, 'M’sila'), (29, 'Mascara'), (30, 'Ouargla'), (31, 'Oran'), (32, 'El Bayadh'), (33, 'Illizi'), (34, 'Bordj'), (35, 'Boumerdès'), (36, 'El-Tarf\t'), (37, 'Tindouf'), (38, 'Tissemsilt'), (39, 'El-Oued\t'), (40, 'Khenchela'), (41, 'Souk-Ahras'), (42, 'Tipaza\t'), (43, 'Mila'), (44, 'Aïn-Defla\t'), (45, 'Naâma'), (46, 'Aïn-Témouchent'), (47, 'Ghardaïa'), (48, 'Relizane'), (49, 'El M-Ghair\t'), (50, 'El Meniaa\t'), (51, 'Ouled Djellal'), (52, 'Bordj Badji '), (53, 'Béni Abbès'), (54, 'Timimoun'), (55, 'Touggourt'), (56, 'Djanet'), (57, 'In Salah'), (58, 'In Guezzam')])),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.user')),
                ('name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.user')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
